# -*- coding: utf-8 -*-
SCHEMA = """
CREATE TABLE groups(id INTEGER PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE subjects(id INTEGER PRIMARY KEY, name TEXT UNIQUE NOT NULL);
CREATE TABLE users(id INTEGER PRIMARY KEY, login TEXT UNIQUE NOT NULL, pw TEXT NOT NULL, name TEXT NOT NULL,
  role TEXT NOT NULL, group_id INTEGER REFERENCES groups(id));
CREATE TABLE assignments(id INTEGER PRIMARY KEY,
  teacher_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE, UNIQUE(teacher_id, group_id, subject_id));
CREATE TABLE lessons(id INTEGER PRIMARY KEY,
  group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  day TEXT NOT NULL, topic TEXT DEFAULT '', teacher_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE(group_id, subject_id, day));
CREATE TABLE marks(student_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  lesson_id INTEGER NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  present INTEGER, grade INTEGER, PRIMARY KEY(student_id, lesson_id));
CREATE TABLE announcements(id INTEGER PRIMARY KEY, author_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  group_id INTEGER REFERENCES groups(id) ON DELETE CASCADE, title TEXT NOT NULL, body TEXT NOT NULL, created TEXT NOT NULL);
"""

NEW_SCHEMA = """
CREATE TABLE IF NOT EXISTS bells(id INTEGER PRIMARY KEY, num INTEGER UNIQUE NOT NULL, start TEXT NOT NULL, end TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS schedule(id INTEGER PRIMARY KEY,
  group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  teacher_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bell_id INTEGER NOT NULL REFERENCES bells(id) ON DELETE CASCADE,
  weekday INTEGER, day TEXT, room TEXT DEFAULT '', parity INTEGER NOT NULL DEFAULT 0,
  teachers_extra TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS changes(id INTEGER PRIMARY KEY,
  schedule_id INTEGER NOT NULL REFERENCES schedule(id) ON DELETE CASCADE, day TEXT NOT NULL, kind TEXT NOT NULL,
  teacher_id INTEGER REFERENCES users(id) ON DELETE SET NULL, room TEXT DEFAULT '', note TEXT DEFAULT '', UNIQUE(schedule_id, day));
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE IF NOT EXISTS duties(id INTEGER PRIMARY KEY, group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE, day TEXT NOT NULL,
  student_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, task TEXT NOT NULL DEFAULT 'Дежурный по группе', UNIQUE(group_id, day, student_id));
CREATE TABLE IF NOT EXISTS homework(id INTEGER PRIMARY KEY, group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE, author_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  title TEXT NOT NULL, body TEXT DEFAULT '', due TEXT, created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS hw_done(hw_id INTEGER NOT NULL REFERENCES homework(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, PRIMARY KEY(hw_id, student_id));
CREATE TABLE IF NOT EXISTS hw_attach(id INTEGER PRIMARY KEY,
  hw_id INTEGER NOT NULL REFERENCES homework(id) ON DELETE CASCADE,
  kind TEXT NOT NULL, name TEXT NOT NULL, url TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS hw_notes(hw_id INTEGER NOT NULL REFERENCES homework(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body TEXT DEFAULT '', updated TEXT NOT NULL, PRIMARY KEY(hw_id, student_id));
CREATE TABLE IF NOT EXISTS bonus_points(
  student_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  balance INTEGER NOT NULL DEFAULT 0,
  conditions TEXT NOT NULL DEFAULT '',
  updated TEXT,
  PRIMARY KEY(student_id, subject_id));
CREATE TABLE IF NOT EXISTS bonus_applications(
  id INTEGER PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  lesson_id INTEGER NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  points_used INTEGER NOT NULL,
  original_grade INTEGER NOT NULL,
  new_grade INTEGER NOT NULL,
  applied_at TEXT NOT NULL,
  cancelled_at TEXT,
  cancelled_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE(student_id, lesson_id));
CREATE TABLE IF NOT EXISTS bonus_rules(
  group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  conditions TEXT NOT NULL DEFAULT '',
  updated TEXT,
  PRIMARY KEY(group_id, subject_id));
CREATE TABLE IF NOT EXISTS bonus_log(
  id INTEGER PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  teacher_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  delta INTEGER NOT NULL,
  reason TEXT NOT NULL DEFAULT '',
  created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS journal_access(
  teacher_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  level TEXT NOT NULL DEFAULT 'edit',
  granted_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created TEXT,
  PRIMARY KEY(teacher_id, group_id, subject_id));
CREATE TABLE IF NOT EXISTS final_grades(
  id INTEGER PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  grade TEXT,
  date_from TEXT,
  date_to TEXT,
  note TEXT DEFAULT '',
  set_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  updated TEXT,
  UNIQUE(student_id, subject_id, kind));
CREATE TABLE IF NOT EXISTS active_sessions(
  token TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS notifications(
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT DEFAULT '',
  link TEXT DEFAULT '',
  created TEXT NOT NULL,
  read INTEGER NOT NULL DEFAULT 0);

"""

